@startuml
skinparam componentStyle rectangle


skinparam package<<Layout>> {
    borderColor Transparent
    backgroundColor Transparent
    '  fontColor Transparent
    stereotypeFontColor Transparent
}

package users <<Layout>> {
    :Visitor: -[hidden]r- :Admin:
    :Admin: -[hidden]r- :Instructor:
    :Instructor: -[hidden]r- :Student:
}

package Controllers <<Layout>> {

    package AdminController {
        [admin1]
    }

    package EnrollmentController {
        [enrol1]
    }

    package CourseController {
        [GET \n/api/courses]        -[hidden]r- [GET \n/api/courses/{id}]
        [GET \n/api/courses/{id}]   -[hidden]r- [POST \n/api/courses]
        [POST \n/api/courses]       -[hidden]r- [PUT  \n/api/courses/{id}]
        [PUT  \n/api/courses/{id}]  -[hidden]r- [DELETE \n/api/courses/{id}]
    }

    package AuthController {
        [POST \n/api/auth/register] -[hidden]r- [POST \n/api/auth/login]
    }

}

package Services <<Layout>> {

    package EnrollmentService {
        [ietsEnroll]
    }

    package CourseService {
        [CreateCourse]
    }

    package AuthService {
        [AuthService.registerUser]
        [AuthService.login]
        [AuthService.GetAllUsers]
    }

}

package repositories <<Layout>> {
    [CourseRepository]
    [UserRepository]
    [EnrollmentRepository]
    [CustomEnrollmentRepository]
}

' LAYOUT Hidden connections horizontal:
' place rectangles per layer in desired order.

'controller
[POST \n/api/auth/login]        -[hidden]r- [GET \n/api/courses]
[DELETE \n/api/courses/{id}]    -[hidden]r- [enrol1]

'service
[AuthService.registerUser]  -[hidden]r- [AuthService.login]
[AuthService.login]         -[hidden]r- [AuthService.GetAllUsers]

[UserRepository]            -[hidden]r- [CourseRepository]
[CourseRepository]          -[hidden]r- [EnrollmentRepository]
[EnrollmentRepository]      -[hidden]r- [CustomEnrollmentRepository]

' LAYOUT Hidden connections vertical:
' Use hidden down connections between the first rectangle in each
' layer to encourage all the layers to be left-aligned.
' NOTE: Use longer arrows to force more space between the layers, so
' that the visible arrows can be more clearly distinguished.
' NOTE: Since we later create a *visible* connection from Comp20 to
' Comp10, we omit create a hidden connection here, otherwise the
' visible connection ends up curving to avoid the hidden one.
Visitor                     -[hidden]d- [POST \n/api/auth/register]
[POST \n/api/auth/register] -[hidden]d- AuthService.registerUser
AuthService.registerUser    -[hidden]d- UserRepository

' Visible connections:
' NOTE: Use norank to prevent these visible connections from taking
' prescedence over the hidden connections and breaking the layout,
' *except* for the visible connections which are equivalent to the
' hidden connections that we have omitted.
' todo see experiment/example

@enduml